apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    app: myservice
  name: myservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myservice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: myservice
    spec:
      containers:
      - image: kevindamato/piglatin
        name: myservice
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
